SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD/ HH24:MI:SS') AS 현재날짜시간
FROM DUAL;

SELECT SYSDATE,
TO_CHAR(SYSDATE, 'MM') AS MM
,TO_CHAR(SYSDATE, 'MON') AS MON
,TO_CHAR(SYSDATE, 'MONTH') AS MONTH
,TO_CHAR(SYSDATE, 'DD') AS DD
,TO_CHAR(SYSDATE, 'DY') AS DY
,TO_CHAR(SYSDATE, 'DAY') AS DAY
FROM DUAL;

SELECT EMPNO, ENAME, SAL, COMM, SAL+COMM
, NVL(COMM,0)
, SAL+NVL(COMM,0)
FROM EMP;

SELECT EMPNO, ENAME, JOB, SAL,
    DECODE(JOB,'MANAGER',SAL*1.1,'SALESMAN',SAL*1.05,'ANALYST',SAL,SAL*1.03)AS UPSAL
    FROM EMP;
    
SELECT EMPNO, ENAME, JOB, SAL,
    CASE JOB
    WHEN 'MANAGER' THEN SAL*1.1
    WHEN 'SALESMAN' THEN SAL*1.05
    WHEN 'ANALYST' THEN SAL
    ELSE SAL*1.03
    END AS UPSAL
    FROM EMP; 
    
SELECT SUM(SAL)
FROM EMP;



